[default]
# I know how to spell all 4-letter words.
# buoy, czar (tsar), gage, vale (veil, vail), wear (ware), xyst, and so on.
extend-ignore-identifiers-re = ["^[a-zA-Z]{1,4}$"]
extend-ignore-re = ["(?s)(#|//)\\s*typos:off.*?\\n\\s*(#|//)\\s*typos:on"]
