{ epkgs }:
epkgs.emacsWithPackages (
  with epkgs;
  [
    ace-window
    auctex
    auctex-lua
    avy
    bind-key
    cape
    cdlatex
    chess
    cond-let
    consult
    consult-dir
    consult-flycheck
    consult-lsp
    corfu
    corfu-terminal # TODO: Remove when on 31
    delight
    diminish
    doom-modeline
    embark
    embark-consult
    envrc
    expand-region
    flycheck
    just-ts-mode
    gcmh
    git-gutter
    helpful
    kkp
    lichess
    lsp-haskell
    lsp-mode
    lsp-ui
    marginalia
    markdown-mode
    mct
    move-text
    multiple-cursors
    nix-ts-mode
    no-littering
    orderless
    rustic
    simpleclip
    smartparens
    treesit-auto
    treesit-grammars.with-all-grammars
    undo-tree
    use-package
    vertico
    wgrep
    which-key
    yasnippet
    yasnippet-snippets
  ]
)
