working_directory = "None"

window.option_as_alt = "OnlyLeft"
window.decorations = "None"
window.startup_mode = "Windowed"

mouse.hide_when_typing = true

bell.duration = 0

selection.save_to_clipboard = true

cursor.style.shape = "Block"
cursor.style.blinking = "Never"
