[[keyboard.bindings]]
  key = "Enter"
  mods = "Command"
  action = "ToggleSimpleFullscreen"

[[keyboard.bindings]]
  key = ";"
  mods = "Control"
  chars = "\u001B[59;5u"

[[keyboard.bindings]]
  key = "/"
  mods = "Control"
  chars = "\u001B[47;5u"

[[keyboard.bindings]]
  key = "'"
  mods = "Control"
  chars = "\u001B[44;5u"

[[keyboard.bindings]]
  key = "."
  mods = "Control"
  chars = "\u001B[46;5u"
