[[keyboard.bindings]]
  key = ";"
  mods = "Control"
  chars = "\u001B[59;5u"

[[keyboard.bindings]]
  key = "/"
  mods = "Control"
  chars = "\u001B[47;5u"

[[keyboard.bindings]]
  key = ">"
  mods = "Alt|Shift"
  chars = "\u001B[46;7u"

[[keyboard.bindings]]
  key = "<"
  mods = "Alt|Shift"
  chars = "\u001B[44;7u"

[[keyboard.bindings]]
  key = "<"
  mods = "Alt|Shift"
  chars = "\u001B[44;7u"

[[keyboard.bindings]]
  key = "Enter"
  mods = "Command"
  action = "ToggleSimpleFullscreen"
