setopt (
  autocd
  autocontinue
  autopushd
  clobberempty
  completealiases
  extendedhistory
  globcomplete
  globdots
  histignoredups
  histignorespace
  histverify
  markdirs
  nobeep
  nohistbeep
  noclobber
  nomatch
  nopromptbang
  pipefail
  pushdignoredups
  pushdminus
  printexitvalue
  sharehistory
)

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

alias -- -='cd -'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias c=clear
alias md='mkdir -p'
alias rd=rmdir

# Enable autocompletion
autoload -U compinit && compinit

bindkey ' ' magic-space # don't do history expansion
bindkey -e # emacs key bindings
bindkey '^P' up-line-or-search
bindkey '^N' down-line-or-search
bindkey '^[^f' emacs-forward-word
bindkey '^[^b' emacs-backward-word

function d () {
  if [[ -n $1 ]]; then
    dirs "$@"
  else
    dirs -v | head -n 10
  fi
}
compdef _dirs d

# Source nix profile and run init of programs installed in the profile.
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi
if [ -e "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
  . "$HOME"/.nix-profile/etc/profile.d/hm-session-vars.sh
fi
if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix.sh ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix.sh
fi
if [[ -d "$HOME/.nix-profile/share/zsh-autosuggestions" ]]; then
  . "$HOME/.nix-profile/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi
if [[ -d "$HOME/.nix-profile/share/zsh-syntax-highlighting" ]]; then
  . "$HOME/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
if [[ -d "$XDG_CONFIG_HOME/shell_aliases.zsh" ]]; then
  . "$XDG_CONFIG_HOME/shell_aliases.zsh"
fi
if command -v fzf &> /dev/null; then
  eval "$(fzf --zsh)"
fi
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh --cmd j)"
fi
if command -v direnv &> /dev/null; then
  eval "$(direnv hook zsh)"
fi
if command -v starship &> /dev/null; then
  eval "$(starship init zsh)"
fi