# Rebind prefix to C-; since it's is not set to anything in emacs.
unbind C-b
set -g prefix C-\;
bind \; send-prefix
bind C-\; last-window

set -g default-terminal "xterm-kitty"
set -g base-index 1
set -g history-limit 100000
set -s escape-time "0"

setw -g aggressive-resize "on"
setw -g pane-base-index 1
setw -g clock-mode-style "24"

set -g status-keys "emacs"
set -g mode-keys "emacs"

set -g status on
set -g status-interval 2
set -g status-justify left
set -g status-position bottom
set -g status-left-length 80
set -g status-right-length 80
set -g status-right "%y-%m-%d %H:%M %p "
set -g pane-border-status top
set -g pane-border-format " [#{pane_index}] | #{pane_current_path} #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD) "

# Silence
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g bell-action none
set-window-option -g monitor-activity off

set-option -g set-titles on
set-option -g set-titles-string "[#h] #W"

set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"
set -g set-clipboard on

# Center cursor and window in copy-mode like emacs.
bind-key -T copy-mode C-l send-keys -X scroll-middle

set -g xterm-keys on
set -s extended-keys on
set -as terminal-features '*:RGB' # truecolor
set -as terminal-features 'xterm*:extkeys'

# Use -A to make a new session idempotent.
new-session -A -s 0