add_newline = true

format = """
$username@$hostname $directory
$character
"""
right_format = """
$time
$git_status $git_branch
"""

[character]
success_symbol = "[>](white) [$](bold green)"
error_symbol = "[>](white) [x](bold red)"

[username]
show_always = true
style_user = "bold white"
format = "[$user]($style)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "dimmed italic white"

[directory]
format = "bold white"

[git_branch]
style = "white"
format = "at [$symbol$branch]($style)"
truncation_length = 29
ignore_branches = ["master", "main"]

[git_status]
format = "[\[$ahead_behind$all_status\]]($style)"
style = "bold white"

[time]
format = "[ \[ $time \]]($style)"
use_12hr = false
time_format = "%Y-%m-%d %H:%M:%S%z (%s)"